app:
  name: music2db-client

music:
  path: /junk/kimiside@gmail.com/Music/Песенник
  scan_time: "04:00"
  extensions: [".mp3", ".flac", ".m4a", ".ogg"]

music_db:
  url: http://kimihome.lan
  # url: http://kimipc.lan
  port: 5005
  one_track_endpoint: "/add_track/"
  many_tracks_endpoint: "/add_tracks/"


# Настройки логирования
logging:
  level: "DEBUG"
  show_time: true
  show_path: false
